import 'package:cloud_firestore/cloud_firestore.dart';

/// Utility to seed the database with sample plants
class SeedData {
  static final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  /// Seed 25 sample plants into Firestore
  static Future<void> seedPlants(String nurseryId, String nurseryName) async {
    final plants = [
      {
        'name': 'Monstera Deliciosa',
        'scientificName': 'Monstera deliciosa',
        'category': 'Indoor',
        'description': 'A popular tropical plant with large, glossy leaves that develop dramatic splits and holes as they mature. Perfect for brightening up any indoor space.',
        'imageUrl': 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=800',
        'wateringFrequency': 'Once a week',
        'sunlightRequirement': 'Bright indirect light',
        'soilType': 'Well-draining potting mix',
        'fertilizingSchedule': 'Monthly during growing season',
        'additionalCareNotes': 'Wipe leaves occasionally to remove dust. Provide a moss pole for climbing.',
      },
      {
        'name': 'Snake Plant',
        'scientificName': 'Sansevieria trifasciata',
        'category': 'Indoor',
        'description': 'One of the most tolerant houseplants. Features stiff, upright leaves with striking patterns. Excellent air purifier.',
        'imageUrl': 'https://images.unsplash.com/photo-1593482892540-73c9826d0b5b?w=800',
        'wateringFrequency': 'Every 2-3 weeks',
        'sunlightRequirement': 'Low to bright indirect light',
        'soilType': 'Well-draining cactus mix',
        'fertilizingSchedule': 'Every 2-3 months',
        'additionalCareNotes': 'Very drought tolerant. Allow soil to dry completely between waterings.',
      },
      {
        'name': 'Fiddle Leaf Fig',
        'scientificName': 'Ficus lyrata',
        'category': 'Indoor',
        'description': 'A trendy indoor tree with large, violin-shaped leaves. Makes a stunning statement piece in any room.',
        'imageUrl': 'https://images.unsplash.com/photo-1614594895304-fe7116ac3b58?w=800',
        'wateringFrequency': 'Once a week',
        'sunlightRequirement': 'Bright indirect light',
        'soilType': 'Rich, well-draining potting soil',
        'fertilizingSchedule': 'Monthly in spring and summer',
        'additionalCareNotes': 'Rotate regularly for even growth. Sensitive to temperature changes.',
      },
      {
        'name': 'Pothos',
        'scientificName': 'Epipremnum aureum',
        'category': 'Indoor',
        'description': 'Easy-care trailing plant with heart-shaped leaves. Perfect for beginners and low-light spaces.',
        'imageUrl': 'https://images.unsplash.com/photo-1572688484438-313a6e50c333?w=800',
        'wateringFrequency': 'When soil is dry',
        'sunlightRequirement': 'Low to bright indirect light',
        'soilType': 'Standard potting mix',
        'fertilizingSchedule': 'Every 2-3 months',
        'additionalCareNotes': 'Great for hanging baskets. Can grow in water or soil.',
      },
      {
        'name': 'Peace Lily',
        'scientificName': 'Spathiphyllum',
        'category': 'Indoor',
        'description': 'Elegant plant with glossy leaves and white flower-like bracts. Excellent air purifier.',
        'imageUrl': 'https://images.unsplash.com/photo-1593482892290-867916a049cf?w=800',
        'wateringFrequency': 'Twice a week',
        'sunlightRequirement': 'Low to medium indirect light',
        'soilType': 'Rich, loose potting soil',
        'fertilizingSchedule': 'Every 6 weeks',
        'additionalCareNotes': 'Prefers humidity. Leaves droop when thirsty.',
      },
      {
        'name': 'Rubber Plant',
        'scientificName': 'Ficus elastica',
        'category': 'Indoor',
        'description': 'Bold plant with thick, glossy leaves. Can grow into a beautiful indoor tree.',
        'imageUrl': 'https://images.unsplash.com/photo-1610411086111-bf861a1ecd89?w=800',
        'wateringFrequency': 'Once a week',
        'sunlightRequirement': 'Bright indirect light',
        'soilType': 'Well-draining potting mix',
        'fertilizingSchedule': 'Monthly in growing season',
        'additionalCareNotes': 'Wipe leaves to maintain shine. Can grow quite tall.',
      },
      {
        'name': 'ZZ Plant',
        'scientificName': 'Zamioculcas zamiifolia',
        'category': 'Indoor',
        'description': 'Nearly indestructible plant with shiny, dark green leaves. Perfect for forgetful plant parents.',
        'imageUrl': 'https://images.unsplash.com/photo-1632207691143-643e2a9a9361?w=800',
        'wateringFrequency': 'Every 2-3 weeks',
        'sunlightRequirement': 'Low to bright indirect light',
        'soilType': 'Well-draining cactus mix',
        'fertilizingSchedule': 'Every 3-4 months',
        'additionalCareNotes': 'Extremely drought tolerant. Thrives on neglect.',
      },
      {
        'name': 'Spider Plant',
        'scientificName': 'Chlorophytum comosum',
        'category': 'Indoor',
        'description': 'Easy-care plant with arching leaves and baby plantlets. Great for hanging baskets.',
        'imageUrl': 'https://images.unsplash.com/photo-1572688484438-313a6e50c333?w=800',
        'wateringFrequency': 'Twice a week',
        'sunlightRequirement': 'Bright indirect light',
        'soilType': 'Well-draining potting mix',
        'fertilizingSchedule': 'Every 2 weeks in summer',
        'additionalCareNotes': 'Produces baby plants that can be propagated.',
      },
      {
        'name': 'Aloe Vera',
        'scientificName': 'Aloe barbadensis miller',
        'category': 'Succulents',
        'description': 'Medicinal succulent with thick, gel-filled leaves. Great for skin care and easy to grow.',
        'imageUrl': 'https://images.unsplash.com/photo-1509587584298-0f3b3a3a1797?w=800',
        'wateringFrequency': 'Every 2-3 weeks',
        'sunlightRequirement': 'Bright direct light',
        'soilType': 'Cactus or succulent mix',
        'fertilizingSchedule': 'Once in spring',
        'additionalCareNotes': 'Allow soil to dry completely between waterings.',
      },
      {
        'name': 'Jade Plant',
        'scientificName': 'Crassula ovata',
        'category': 'Succulents',
        'description': 'Lucky plant with thick, woody stems and rounded leaves. Symbol of prosperity.',
        'imageUrl': 'https://images.unsplash.com/photo-1459156212016-c812468e2115?w=800',
        'wateringFrequency': 'Every 2-3 weeks',
        'sunlightRequirement': 'Bright direct light',
        'soilType': 'Succulent or cactus mix',
        'fertilizingSchedule': 'Every 3-4 months',
        'additionalCareNotes': 'Minimal water in winter. Can live for decades.',
      },
      {
        'name': 'Lavender',
        'scientificName': 'Lavandula',
        'category': 'Herbs',
        'description': 'Fragrant herb with purple flowers. Perfect for cooking, aromatherapy, and attracting pollinators.',
        'imageUrl': 'https://images.unsplash.com/photo-1499002238440-d264edd596ec?w=800',
        'wateringFrequency': 'When soil is dry',
        'sunlightRequirement': 'Full sun (6+ hours)',
        'soilType': 'Well-draining sandy soil',
        'fertilizingSchedule': 'Once in spring',
        'additionalCareNotes': 'Prune after flowering. Prefers dry conditions.',
      },
      {
        'name': 'Basil',
        'scientificName': 'Ocimum basilicum',
        'category': 'Herbs',
        'description': 'Popular culinary herb with aromatic leaves. Essential for Italian cooking.',
        'imageUrl': 'https://images.unsplash.com/photo-1618375569909-3c8616cf7733?w=800',
        'wateringFrequency': 'Daily in summer',
        'sunlightRequirement': 'Full sun (6+ hours)',
        'soilType': 'Rich, well-draining soil',
        'fertilizingSchedule': 'Every 2 weeks',
        'additionalCareNotes': 'Pinch flowers to encourage leaf growth. Harvest regularly.',
      },
      {
        'name': 'Tomato',
        'scientificName': 'Solanum lycopersicum',
        'category': 'Vegetables',
        'description': 'Popular garden vegetable producing juicy, flavorful fruits. Great for beginners.',
        'imageUrl': 'https://images.unsplash.com/photo-1546470427-227e2645a79b?w=800',
        'wateringFrequency': 'Daily',
        'sunlightRequirement': 'Full sun (8+ hours)',
        'soilType': 'Rich, well-draining garden soil',
        'fertilizingSchedule': 'Weekly with tomato fertilizer',
        'additionalCareNotes': 'Stake or cage for support. Remove suckers for larger fruits.',
      },
      {
        'name': 'Sunflower',
        'scientificName': 'Helianthus annuus',
        'category': 'Flowering',
        'description': 'Cheerful tall flower that follows the sun. Produces edible seeds.',
        'imageUrl': 'https://images.unsplash.com/photo-1597848212624-e50b21b1ca96?w=800',
        'wateringFrequency': '2-3 times per week',
        'sunlightRequirement': 'Full sun (6-8 hours)',
        'soilType': 'Well-draining garden soil',
        'fertilizingSchedule': 'Monthly',
        'additionalCareNotes': 'Stake tall varieties. Harvest seeds when flower head dries.',
      },
      {
        'name': 'Rose',
        'scientificName': 'Rosa',
        'category': 'Flowering',
        'description': 'Classic flowering plant with fragrant blooms. Symbol of love and beauty.',
        'imageUrl': 'https://images.unsplash.com/photo-1518709594023-6eab9bab7b23?w=800',
        'wateringFrequency': '2-3 times per week',
        'sunlightRequirement': 'Full sun (6+ hours)',
        'soilType': 'Rich, well-draining loamy soil',
        'fertilizingSchedule': 'Monthly during growing season',
        'additionalCareNotes': 'Prune in early spring. Deadhead spent blooms for more flowers.',
      },
      {
        'name': 'Bamboo Palm',
        'scientificName': 'Chamaedorea seifrizii',
        'category': 'Indoor',
        'description': 'Elegant palm with feathery fronds. Excellent air purifier and adds tropical vibes.',
        'imageUrl': 'https://images.unsplash.com/photo-1604424991731-e319d682c410?w=800',
        'wateringFrequency': '2-3 times per week',
        'sunlightRequirement': 'Bright indirect light',
        'soilType': 'Rich, well-draining potting mix',
        'fertilizingSchedule': 'Monthly in growing season',
        'additionalCareNotes': 'Prefers humidity. Mist leaves occasionally.',
      },
      {
        'name': 'English Ivy',
        'scientificName': 'Hedera helix',
        'category': 'Outdoor',
        'description': 'Versatile climbing vine with attractive foliage. Great for ground cover or vertical gardens.',
        'imageUrl': 'https://images.unsplash.com/photo-1598880940371-c756e015faf4?w=800',
        'wateringFrequency': '2-3 times per week',
        'sunlightRequirement': 'Partial shade',
        'soilType': 'Well-draining garden soil',
        'fertilizingSchedule': 'Every 2-3 months',
        'additionalCareNotes': 'Can be invasive. Trim regularly to control growth.',
      },
      {
        'name': 'Boston Fern',
        'scientificName': 'Nephrolepis exaltata',
        'category': 'Indoor',
        'description': 'Lush fern with graceful arching fronds. Perfect for hanging baskets.',
        'imageUrl': 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=800',
        'wateringFrequency': 'Keep soil moist',
        'sunlightRequirement': 'Bright indirect light',
        'soilType': 'Rich, well-draining potting soil',
        'fertilizingSchedule': 'Monthly in growing season',
        'additionalCareNotes': 'Loves humidity. Mist daily or use a humidifier.',
      },
      {
        'name': 'Orchid',
        'scientificName': 'Phalaenopsis',
        'category': 'Flowering',
        'description': 'Elegant flowering plant with long-lasting blooms. Symbol of luxury and beauty.',
        'imageUrl': 'https://images.unsplash.com/photo-1586107920032-a6d60a63f928?w=800',
        'wateringFrequency': 'Once a week',
        'sunlightRequirement': 'Bright indirect light',
        'soilType': 'Orchid bark mix',
        'fertilizingSchedule': 'Weekly with diluted orchid fertilizer',
        'additionalCareNotes': 'Water in morning. Allow to dry slightly between waterings.',
      },
      {
        'name': 'Cactus',
        'scientificName': 'Cactaceae',
        'category': 'Succulents',
        'description': 'Low-maintenance desert plant with unique shapes. Perfect for forgetful waterers.',
        'imageUrl': 'https://images.unsplash.com/photo-1509587584298-0f3b3a3a1797?w=800',
        'wateringFrequency': 'Every 3-4 weeks',
        'sunlightRequirement': 'Bright direct light',
        'soilType': 'Cactus mix',
        'fertilizingSchedule': 'Once in spring and summer',
        'additionalCareNotes': 'Minimal water in winter. Handle with care (spines!).',
      },
      {
        'name': 'Mint',
        'scientificName': 'Mentha',
        'category': 'Herbs',
        'description': 'Refreshing herb perfect for teas, cocktails, and cooking. Grows vigorously.',
        'imageUrl': 'https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=800',
        'wateringFrequency': 'Keep soil moist',
        'sunlightRequirement': 'Partial shade to full sun',
        'soilType': 'Rich, moist potting soil',
        'fertilizingSchedule': 'Monthly',
        'additionalCareNotes': 'Very invasive - grow in containers. Harvest frequently.',
      },
      {
        'name': 'Rosemary',
        'scientificName': 'Rosmarinus officinalis',
        'category': 'Herbs',
        'description': 'Aromatic woody herb perfect for cooking. Drought-tolerant and fragrant.',
        'imageUrl': 'https://images.unsplash.com/photo-1618375569909-3c8616cf7733?w=800',
        'wateringFrequency': 'When soil is dry',
        'sunlightRequirement': 'Full sun (6+ hours)',
        'soilType': 'Well-draining sandy soil',
        'fertilizingSchedule': 'Once in spring',
        'additionalCareNotes': 'Prune regularly. Prefers dry conditions.',
      },
      {
        'name': 'Lettuce',
        'scientificName': 'Lactuca sativa',
        'category': 'Vegetables',
        'description': 'Fast-growing leafy vegetable. Perfect for salads and sandwiches.',
        'imageUrl': 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=800',
        'wateringFrequency': 'Daily',
        'sunlightRequirement': 'Partial shade to full sun',
        'soilType': 'Rich, well-draining soil',
        'fertilizingSchedule': 'Every 2 weeks',
        'additionalCareNotes': 'Harvest outer leaves. Grows quickly in cool weather.',
      },
      {
        'name': 'Marigold',
        'scientificName': 'Tagetes',
        'category': 'Flowering',
        'description': 'Bright, cheerful flowers that repel pests. Easy to grow annual.',
        'imageUrl': 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?w=800',
        'wateringFrequency': '2-3 times per week',
        'sunlightRequirement': 'Full sun',
        'soilType': 'Well-draining garden soil',
        'fertilizingSchedule': 'Every 3-4 weeks',
        'additionalCareNotes': 'Deadhead for continuous blooms. Natural pest repellent.',
      },
      {
        'name': 'Bell Pepper',
        'scientificName': 'Capsicum annuum',
        'category': 'Vegetables',
        'description': 'Colorful vegetable rich in vitamins. Great for salads and cooking.',
        'imageUrl': 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=800',
        'wateringFrequency': 'Daily',
        'sunlightRequirement': 'Full sun (6-8 hours)',
        'soilType': 'Rich, well-draining soil',
        'fertilizingSchedule': 'Every 2 weeks',
        'additionalCareNotes': 'Support with stakes. Harvest when fully colored.',
      },
      {
        'name': 'Calathea',
        'scientificName': 'Calathea ornata',
        'category': 'Indoor',
        'description': 'Stunning tropical plant with beautifully patterned leaves. Leaves fold up at night.',
        'imageUrl': 'https://images.unsplash.com/photo-1503403412219-a28e6b6fcb8d?w=800',
        'wateringFrequency': '2-3 times per week',
        'sunlightRequirement': 'Medium indirect light',
        'soilType': 'Peaty, well-draining mix',
        'fertilizingSchedule': 'Every 2 weeks in growing season',
        'additionalCareNotes': 'Loves humidity. Use distilled or filtered water.',
      },
      {
        'name': 'Bird of Paradise',
        'scientificName': 'Strelitzia reginae',
        'category': 'Indoor',
        'description': 'Dramatic tropical plant with large banana-like leaves. Can produce stunning orange flowers.',
        'imageUrl': 'https://images.unsplash.com/photo-1584462040122-e702b57eff90?w=800',
        'wateringFrequency': 'Once a week',
        'sunlightRequirement': 'Bright indirect to direct light',
        'soilType': 'Rich, well-draining potting mix',
        'fertilizingSchedule': 'Monthly during spring and summer',
        'additionalCareNotes': 'Needs space to grow. Wipe leaves regularly.',
      },
      {
        'name': 'Chinese Money Plant',
        'scientificName': 'Pilea peperomioides',
        'category': 'Indoor',
        'description': 'Cute plant with round, coin-shaped leaves. Easy to propagate and share.',
        'imageUrl': 'https://images.unsplash.com/photo-1572688485383-5dac2c1876e4?w=800',
        'wateringFrequency': 'Once a week',
        'sunlightRequirement': 'Bright indirect light',
        'soilType': 'Well-draining potting mix',
        'fertilizingSchedule': 'Every 2 weeks in growing season',
        'additionalCareNotes': 'Rotate regularly for even growth. Produces many babies!',
      },
      {
        'name': 'Boston Fern',
        'scientificName': 'Nephrolepis exaltata',
        'category': 'Indoor',
        'description': 'Classic houseplant with lush, feathery fronds. Excellent for hanging baskets.',
        'imageUrl': 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=800',
        'wateringFrequency': 'Keep soil consistently moist',
        'sunlightRequirement': 'Medium to bright indirect light',
        'soilType': 'Rich, peat-based mix',
        'fertilizingSchedule': 'Every 2-4 weeks',
        'additionalCareNotes': 'Loves humidity. Mist regularly or use humidifier.',
      },
      {
        'name': 'Philodendron Brasil',
        'scientificName': 'Philodendron hederaceum',
        'category': 'Indoor',
        'description': 'Vibrant trailing plant with heart-shaped leaves in green and yellow variegation.',
        'imageUrl': 'https://images.unsplash.com/photo-1545241047-6783497f569e?w=800',
        'wateringFrequency': 'When top inch is dry',
        'sunlightRequirement': 'Medium to bright indirect light',
        'soilType': 'Well-draining potting mix',
        'fertilizingSchedule': 'Monthly',
        'additionalCareNotes': 'Very easy to care for. Great for beginners.',
      },
      {
        'name': 'Jade Plant',
        'scientificName': 'Crassula ovata',
        'category': 'Succulents',
        'description': 'Lucky plant with thick, glossy leaves. Can live for decades with proper care.',
        'imageUrl': 'https://images.unsplash.com/photo-1459156212016-c812468e2115?w=800',
        'wateringFrequency': 'Every 2-3 weeks',
        'sunlightRequirement': 'Bright light with some direct sun',
        'soilType': 'Cactus/succulent mix',
        'fertilizingSchedule': 'Every 2-3 months',
        'additionalCareNotes': 'Easy to propagate from leaves. Drought tolerant.',
      },
      {
        'name': 'String of Pearls',
        'scientificName': 'Senecio rowleyanus',
        'category': 'Succulents',
        'description': 'Unique trailing succulent with bead-like leaves. Perfect for hanging planters.',
        'imageUrl': 'https://images.unsplash.com/photo-1505066951768-bbe3f155ea84?w=800',
        'wateringFrequency': 'Every 2 weeks',
        'sunlightRequirement': 'Bright indirect light',
        'soilType': 'Cactus/succulent mix',
        'fertilizingSchedule': 'Every 4-6 weeks',
        'additionalCareNotes': 'Bottom water for best results. Avoid overwatering.',
      },
      {
        'name': 'Hoya',
        'scientificName': 'Hoya carnosa',
        'category': 'Indoor',
        'description': 'Wax plant with thick, waxy leaves and fragrant star-shaped flowers.',
        'imageUrl': 'https://images.unsplash.com/photo-1509423350716-97f9360b4e09?w=800',
        'wateringFrequency': 'When soil is completely dry',
        'sunlightRequirement': 'Bright indirect light',
        'soilType': 'Well-draining orchid or succulent mix',
        'fertilizingSchedule': 'Monthly in growing season',
        'additionalCareNotes': 'Very long-lived. Flowers more with age.',
      },
      {
        'name': 'Alocasia',
        'scientificName': 'Alocasia amazonica',
        'category': 'Indoor',
        'description': 'Dramatic plant with arrow-shaped leaves and striking white veins.',
        'imageUrl': 'https://images.unsplash.com/photo-1584589934179-98ab469fe046?w=800',
        'wateringFrequency': '2-3 times per week',
        'sunlightRequirement': 'Bright indirect light',
        'soilType': 'Rich, well-draining mix',
        'fertilizingSchedule': 'Every 2 weeks in summer',
        'additionalCareNotes': 'Needs humidity. Can go dormant in winter.',
      },
      {
        'name': 'English Ivy',
        'scientificName': 'Hedera helix',
        'category': 'Indoor',
        'description': 'Classic trailing plant with lobed leaves. Great air purifier.',
        'imageUrl': 'https://images.unsplash.com/photo-1603994620957-ce1c1d1fd3fe?w=800',
        'wateringFrequency': '2-3 times per week',
        'sunlightRequirement': 'Medium to bright indirect light',
        'soilType': 'Well-draining potting mix',
        'fertilizingSchedule': 'Monthly',
        'additionalCareNotes': 'Prefers cooler temperatures. Mist regularly.',
      },
      {
        'name': 'Dieffenbachia',
        'scientificName': 'Dieffenbachia seguine',
        'category': 'Indoor',
        'description': 'Bold tropical plant with large variegated leaves. Also called dumb cane.',
        'imageUrl': 'https://images.unsplash.com/photo-1542279789-be28f5ddf268?w=800',
        'wateringFrequency': 'When top 2 inches dry',
        'sunlightRequirement': 'Medium to bright indirect light',
        'soilType': 'Peat-based potting mix',
        'fertilizingSchedule': 'Every 2 weeks in growing season',
        'additionalCareNotes': 'Keep away from pets. Toxic if ingested.',
      },
      {
        'name': 'Asparagus Fern',
        'scientificName': 'Asparagus setaceus',
        'category': 'Indoor',
        'description': 'Delicate, feathery plant that adds softness to any space. Not a true fern.',
        'imageUrl': 'https://images.unsplash.com/photo-1590256739394-f6279a7cf157?w=800',
        'wateringFrequency': '2-3 times per week',
        'sunlightRequirement': 'Bright indirect light',
        'soilType': 'Rich, well-draining mix',
        'fertilizingSchedule': 'Monthly',
        'additionalCareNotes': 'Loves humidity. Can produce small white flowers.',
      },
      {
        'name': 'Croton',
        'scientificName': 'Codiaeum variegatum',
        'category': 'Indoor',
        'description': 'Vibrant tropical plant with multicolored leaves in red, orange, yellow, and green.',
        'imageUrl': 'https://images.unsplash.com/photo-1585317457001-b3a2b2b4f23f?w=800',
        'wateringFrequency': 'When top inch is dry',
        'sunlightRequirement': 'Bright light with some direct sun',
        'soilType': 'Well-draining potting mix',
        'fertilizingSchedule': 'Every 2 weeks in spring and summer',
        'additionalCareNotes': 'More light = more color. Likes humidity.',
      },
      {
        'name': 'Orchid',
        'scientificName': 'Phalaenopsis',
        'category': 'Flowers',
        'description': 'Elegant flowering plant with long-lasting blooms. Perfect gift plant.',
        'imageUrl': 'https://images.unsplash.com/photo-1518623001395-125242310d0c?w=800',
        'wateringFrequency': 'Once a week (ice cube method)',
        'sunlightRequirement': 'Bright indirect light',
        'soilType': 'Orchid bark mix',
        'fertilizingSchedule': 'Weekly with diluted fertilizer',
        'additionalCareNotes': 'Flowers last months. Can rebloom with proper care.',
      },
      {
        'name': 'Peperomia',
        'scientificName': 'Peperomia obtusifolia',
        'category': 'Indoor',
        'description': 'Compact plant with thick, glossy leaves. Many varieties available.',
        'imageUrl': 'https://images.unsplash.com/photo-1502363703-0a69c9c2ed18?w=800',
        'wateringFrequency': 'Every 1-2 weeks',
        'sunlightRequirement': 'Medium to bright indirect light',
        'soilType': 'Well-draining potting mix',
        'fertilizingSchedule': 'Monthly',
        'additionalCareNotes': 'Very low maintenance. Great for small spaces.',
      },
      {
        'name': 'Anthurium',
        'scientificName': 'Anthurium andraeanum',
        'category': 'Flowers',
        'description': 'Tropical plant with glossy heart-shaped flowers in red, pink, or white.',
        'imageUrl': 'https://images.unsplash.com/photo-1601362840469-51e4d8d58785?w=800',
        'wateringFrequency': 'When top inch is dry',
        'sunlightRequirement': 'Bright indirect light',
        'soilType': 'Orchid mix or peat-based',
        'fertilizingSchedule': 'Every 2 weeks in growing season',
        'additionalCareNotes': 'Loves humidity. Flowers last for months.',
      },
      {
        'name': 'Dracaena',
        'scientificName': 'Dracaena fragrans',
        'category': 'Indoor',
        'description': 'Architectural plant with striped, sword-like leaves. Great for corners.',
        'imageUrl': 'https://images.unsplash.com/photo-1599074749470-105cf0697206?w=800',
        'wateringFrequency': 'When top 2 inches dry',
        'sunlightRequirement': 'Medium to bright indirect light',
        'soilType': 'Well-draining potting mix',
        'fertilizingSchedule': 'Monthly in growing season',
        'additionalCareNotes': 'Very tolerant. Can grow quite tall.',
      },
      {
        'name': 'Strawberry',
        'scientificName': 'Fragaria × ananassa',
        'category': 'Fruits',
        'description': 'Sweet berry plant that can be grown in containers. Produces runners.',
        'imageUrl': 'https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?w=800',
        'wateringFrequency': 'Daily in fruiting season',
        'sunlightRequirement': 'Full sun (6-8 hours)',
        'soilType': 'Rich, slightly acidic soil',
        'fertilizingSchedule': 'Every 2 weeks',
        'additionalCareNotes': 'Harvest when fully red. Mulch to prevent rot.',
      },
      {
        'name': 'Blueberry Bush',
        'scientificName': 'Vaccinium corymbosum',
        'category': 'Fruits',
        'description': 'Delicious berry bush with beautiful fall colors. Needs acidic soil.',
        'imageUrl': 'https://images.unsplash.com/photo-1499689496495-5d0266bec727?w=800',
        'wateringFrequency': '2-3 times per week',
        'sunlightRequirement': 'Full sun',
        'soilType': 'Acidic, well-draining soil (pH 4.5-5.5)',
        'fertilizingSchedule': 'Monthly with acidic fertilizer',
        'additionalCareNotes': 'Needs 2 varieties for cross-pollination.',
      },
      {
        'name': 'Cucumber',
        'scientificName': 'Cucumis sativus',
        'category': 'Vegetables',
        'description': 'Fast-growing vegetable plant. Great for fresh salads and pickling.',
        'imageUrl': 'https://images.unsplash.com/photo-1568584711271-9b07a555d7b8?w=800',
        'wateringFrequency': 'Daily',
        'sunlightRequirement': 'Full sun (6-8 hours)',
        'soilType': 'Rich, well-draining soil',
        'fertilizingSchedule': 'Weekly',
        'additionalCareNotes': 'Provide trellis for climbing. Harvest regularly.',
      },
      {
        'name': 'Carrot',
        'scientificName': 'Daucus carota',
        'category': 'Vegetables',
        'description': 'Root vegetable rich in beta-carotene. Great for containers.',
        'imageUrl': 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=800',
        'wateringFrequency': 'Consistently moist',
        'sunlightRequirement': 'Full sun',
        'soilType': 'Loose, sandy soil',
        'fertilizingSchedule': 'Every 3 weeks',
        'additionalCareNotes': 'Thin seedlings. Deep soil needed for long carrots.',
      },
      {
        'name': 'Zucchini',
        'scientificName': 'Cucurbita pepo',
        'category': 'Vegetables',
        'description': 'Prolific summer squash. One plant produces many fruits.',
        'imageUrl': 'https://images.unsplash.com/photo-1598381913914-ad92e031f64e?w=800',
        'wateringFrequency': 'Daily in hot weather',
        'sunlightRequirement': 'Full sun (6-8 hours)',
        'soilType': 'Rich, well-draining soil',
        'fertilizingSchedule': 'Every 2 weeks',
        'additionalCareNotes': 'Harvest young for best flavor. Very productive!',
      },
      {
        'name': 'Sunflower',
        'scientificName': 'Helianthus annuus',
        'category': 'Flowers',
        'description': 'Cheerful tall flower that follows the sun. Produces edible seeds.',
        'imageUrl': 'https://images.unsplash.com/photo-1508615039623-a25605d2b022?w=800',
        'wateringFrequency': 'Every 2-3 days',
        'sunlightRequirement': 'Full sun (6-8 hours)',
        'soilType': 'Well-draining soil',
        'fertilizingSchedule': 'Monthly',
        'additionalCareNotes': 'May need staking. Attracts birds and bees.',
      },
      {
        'name': 'Catnip',
        'scientificName': 'Nepeta cataria',
        'category': 'Herbs',
        'description': 'Aromatic herb loved by cats. Also makes calming tea for humans.',
        'imageUrl': 'https://images.unsplash.com/photo-1517650862521-d580d5348145?w=800',
        'wateringFrequency': 'When soil is dry',
        'sunlightRequirement': 'Full sun to partial shade',
        'soilType': 'Well-draining sandy soil',
        'fertilizingSchedule': 'Every 4-6 weeks',
        'additionalCareNotes': 'Very easy to grow. Can become invasive.',
      },
    ];

    final batch = _firestore.batch();
    
    for (var plantData in plants) {
      final docRef = _firestore.collection('plants').doc();
      final qrCode = 'plant_${docRef.id}';
      
      batch.set(docRef, {
        ...plantData,
        'nurseryId': nurseryId,
        'nurseryName': nurseryName,
        'createdAt': FieldValue.serverTimestamp(),
        'viewCount': 0,
        'qrCode': qrCode,
      });
    }

    await batch.commit();
    print('✅ Successfully seeded ${plants.length} plants!');
  }

  /// Check if database already has plants
  static Future<bool> hasPlants() async {
    final snapshot = await _firestore.collection('plants').limit(1).get();
    return snapshot.docs.isNotEmpty;
  }

  /// Seed data if database is empty
  static Future<void> seedIfEmpty(String nurseryId, String nurseryName) async {
    if (!await hasPlants()) {
      print('🌱 Seeding plant database...');
      await seedPlants(nurseryId, nurseryName);
    } else {
      print('✅ Database already has plants');
    }
  }
}