import 'package:cloud_firestore/cloud_firestore.dart';

/// Reminder data model
/// Represents a care reminder for a specific plant
/// Primary domain: Person 3 (Reminders)
class ReminderModel {
  final String id;
  final String userId;
  final String plantId;
  final String plantName;
  final String type; // 'watering', 'fertilizing', 'pruning', 'repotting', 'pest_control', 'general_care'
  final String title;
  final String? description;
  
  // Scheduling
  final DateTime scheduledTime;
  bool isRecurring;
  String? recurringPattern; // 'daily', 'weekly', 'bi_weekly', 'monthly', 'every_X_days'
  
  // Status
  bool isCompleted;
  DateTime? completedAt;
  bool isEnabled;
  final bool isAutoGenerated; // True if created automatically from plant care needs
  
  // Metadata
  final DateTime createdAt;
  final DateTime? updatedAt;
  final int snoozeCount;
  final DateTime? lastSnoozedAt;

  ReminderModel({
    required this.id,
    required this.userId,
    required this.plantId,
    required this.plantName,
    required this.type,
    required this.title,
    this.description,
    required this.scheduledTime,
    this.isRecurring = false,
    this.recurringPattern,
    this.isCompleted = false,
    this.completedAt,
    this.isEnabled = true,
    this.isAutoGenerated = false,
    required this.createdAt,
    this.updatedAt,
    this.snoozeCount = 0,
    this.lastSnoozedAt,
  });

  /// Create ReminderModel from Firestore document
  factory ReminderModel.fromFirestore(DocumentSnapshot doc) {
    final data = doc.data() as Map<String, dynamic>;
    
    return ReminderModel(
      id: doc.id,
      userId: data['userId'] ?? '',
      plantId: data['plantId'] ?? '',
      plantName: data['plantName'] ?? '',
      type: data['type'] ?? data['careType'] ?? 'watering',
      title: data['title'] ?? '',
      description: data['description'],
      scheduledTime: (data['scheduledTime'] as Timestamp).toDate(),
      isRecurring: data['isRecurring'] ?? false,
      recurringPattern: data['recurringPattern'],
      isCompleted: data['isCompleted'] ?? false,
      completedAt: data['completedAt'] != null
          ? (data['completedAt'] as Timestamp).toDate()
          : null,
      isEnabled: data['isEnabled'] ?? data['isActive'] ?? true,
      isAutoGenerated: data['isAutoGenerated'] ?? false,
      createdAt: data['createdAt'] != null 
          ? (data['createdAt'] as Timestamp).toDate()
          : DateTime.now(),
      updatedAt: data['updatedAt'] != null
          ? (data['updatedAt'] as Timestamp).toDate()
          : null,
      snoozeCount: data['snoozeCount'] ?? 0,
      lastSnoozedAt: data['lastSnoozedAt'] != null
          ? (data['lastSnoozedAt'] as Timestamp).toDate()
          : null,
    );
  }

  /// Convert ReminderModel to Firestore-compatible map
  Map<String, dynamic> toFirestore() {
    return {
      'userId': userId,
      'plantId': plantId,
      'plantName': plantName,
      'type': type,
      'title': title,
      'description': description,
      'scheduledTime': Timestamp.fromDate(scheduledTime),
      'isRecurring': isRecurring,
      'recurringPattern': recurringPattern,
      'isCompleted': isCompleted,
      'completedAt': completedAt != null 
          ? Timestamp.fromDate(completedAt!) 
          : null,
      'isEnabled': isEnabled,
      'isAutoGenerated': isAutoGenerated,
      'createdAt': Timestamp.fromDate(createdAt),
      'updatedAt': updatedAt != null ? Timestamp.fromDate(updatedAt!) : null,
      'snoozeCount': snoozeCount,
      'lastSnoozedAt': lastSnoozedAt != null
          ? Timestamp.fromDate(lastSnoozedAt!)
          : null,
    };
  }

  /// Create a copy with updated fields
  ReminderModel copyWith({
    String? title,
    String? description,
    DateTime? scheduledTime,
    bool? isRecurring,
    String? recurringPattern,
    bool? isCompleted,
    DateTime? completedAt,
    bool? isEnabled,
    DateTime? updatedAt,
    int? snoozeCount,
    DateTime? lastSnoozedAt,
  }) {
    return ReminderModel(
      id: id,
      userId: userId,
      plantId: plantId,
      plantName: plantName,
      type: type,
      title: title ?? this.title,
      description: description ?? this.description,
      scheduledTime: scheduledTime ?? this.scheduledTime,
      isRecurring: isRecurring ?? this.isRecurring,
      recurringPattern: recurringPattern ?? this.recurringPattern,
      isCompleted: isCompleted ?? this.isCompleted,
      completedAt: completedAt ?? this.completedAt,
      isEnabled: isEnabled ?? this.isEnabled,
      isAutoGenerated: isAutoGenerated,
      createdAt: createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      snoozeCount: snoozeCount ?? this.snoozeCount,
      lastSnoozedAt: lastSnoozedAt ?? this.lastSnoozedAt,
    );
  }

  /// Check if reminder is overdue
  bool get isOverdue =>
      !isCompleted && scheduledTime.isBefore(DateTime.now());

  /// Check if reminder is due today
  bool get isDueToday {
    final now = DateTime.now();
    final scheduled = scheduledTime;
    return !isCompleted &&
        scheduled.year == now.year &&
        scheduled.month == now.month &&
        scheduled.day == now.day;
  }
  
  /// Get human-readable frequency text
  String get frequencyText {
    if (!isRecurring || recurringPattern == null) return 'One-time';
    
    switch (recurringPattern) {
      case 'daily':
        return 'Daily';
      case 'every_2_days':
        return 'Every 2 days';
      case 'every_3_days':
        return 'Every 3 days';
      case 'weekly':
        return 'Weekly';
      case 'bi_weekly':
        return 'Bi-weekly';
      case 'monthly':
        return 'Monthly';
      default:
        return recurringPattern!.replaceAll('_', ' ');
    }
  }
}

